Keep Old Student Submissions
kippnorcal/google_classroom pull request #99
Opened 2020-08-21 22:27 UTC by zkagin

Fixes #91 

Instead of dropping and rewriting the student submissions database, this endpoint now appends new files and then removes duplicates based on the updateTime. This PR also adds some new testing functionality to allow for alternate return values so that it can properly test getting a value that needs to be updated.

I tested a different approach where it would delete rows as it found new ones that needed to be updated, but I think the performance tradeoff is too significant for it to be worth it. I don't love having raw SQL DELETE functionality, but I think given the limitations of bulk deleting by ID, SQL seems by far the most performant option.

2020-09-24 16:51 UTC, dchess requested changes
The row number logic in the duplicate removals code needs revision to prevent false positives.

2020-09-24 16:51 UTC, dchess commented on google_classroom/sql/remove_duplicates.sql
> +                id
@zkagin The id field in the submission table is none unique. I ran some tests of this query (without the delete) to see how many records it detected before even running any appends and I found many records that would be flagged for deletion. It looks like submissions can have the same id but a with different courseWorkId.

2020-09-25 03:19 UTC, dchess commented
@zkagin switching this to merge into main now that it is the default branch instead of master.

2020-09-30 03:50 UTC, zkagin commented on google_classroom/sql/remove_duplicates.sql
> +WITH
Are you thinking that we merge the new table with the old data, dedupe via pandas, drop/empty the table, and then write the newly deduped version? It has been awhile since I tried the different approaches, but I don't recall trying this one, so perhaps it could work. Should I explore this option?

2020-09-30 03:56 UTC, zkagin commented on google_classroom/sql/remove_duplicates.sql
> +                id
Weird, in the data I have ID seems to be unique. Can you run the query below and see if you get numbers other than 1? I'll test things out and see if I can see what you're seeing as well.
```
SELECT
    ct,
    count(1)
FROM (
    SELECT
        id,
        count(1) as ct
    FROM "GoogleClassroom_StudentSubmissions"
    GROUP BY id
) sub
GROUP BY ct;
```

2020-09-30 14:44 UTC, dchess commented on google_classroom/sql/remove_duplicates.sql
> +                id
@zkagin That query returns 42 records with ct=2. It's a small fraction, but still significant for us.

2020-09-30 14:46 UTC, dchess commented on google_classroom/sql/remove_duplicates.sql
> +WITH
That was my thinking originally, but given the recent problems with the memory error, I'm concerned we'd have to scale up the server resources significantly to support that approach.

2020-10-02 05:19 UTC, zkagin commented on google_classroom/sql/remove_duplicates.sql
> +                id
This is strange, I just pulled the latest course list and student submissions from KIPP and am getting a count of 1 for everything. Let's hop on a call and see if we can figure out what the difference is.

2020-10-03 00:51 UTC, dchess commented on google_classroom/sql/remove_duplicates.sql
> +                id
@zkagin Sounds good. Can you propose a time using my calendly link?

2020-10-08 17:05 UTC, dchess commented on google_classroom/sql/remove_duplicates.sql
> +                id
@zkagin Surprisingly, this works as expected:
```sql
SELECT
    ct,
    count(1)
FROM (
    SELECT
        id,
        count(DISTINCT id) as ct
    FROM custom.GoogleClassroom_StudentSubmissions
    GROUP BY id
) sub
GROUP BY ct
```

I'm wondering if we tweak the raw SQL to include `DISTINCT` in the subquery if this would actually work. Although still interested to hear if the pandas drop_duplicates approach is functional.

2020-10-14 23:16 UTC, zkagin commented on google_classroom/sql/remove_duplicates.sql
> +WITH
#108 is an attempt at doing this.

2020-10-14 23:17 UTC, zkagin commented
Confirmed that the duplicate ID issue was because MSSQL is not case-sensitive in the GROUP BY and there are different IDs with the same letters/numbers but in different cases, so if we use this SQL we will need to find a way to get it working there.

2020-10-14 23:24 UTC, dchess commented
@zkagin Did you test it with adding a COUNT DISTINCT in the subquery with MS SQL and Postgres?

2020-10-15 00:08 UTC, zkagin commented
@dchess There's no count in the query in the PR — can you explain more what you wanted to test?

I found a solution to force MSSQL to be case sensitive, but it only works for MSSQL. I can't think of anything that'd work across all types of SQL unless we process and substitute the ID for something else (like an md5 hash) outside of SQL. This could also be a place where we could add functionality to SQLSorcery to handle this.

What do you think?

```
WITH
    duplicates
    AS
    (
        SELECT
            id COLLATE SQL_Latin1_General_CP1_CS_AS AS id, assignedGrade, updateTime,
            ROW_NUMBER() OVER (
            PARTITION BY
                id COLLATE SQL_Latin1_General_CP1_CS_AS
            ORDER BY
                updateTime
            DESC
        ) row_num
        FROM GoogleClassroom_StudentSubmissions
    )
DELETE
FROM duplicates
WHERE row_num > 1;
```

2020-10-15 00:14 UTC, zkagin commented
@dchess For the time being I can also just have two files and use the config to run the MSSQL one as needed. Hacky, but also it seems pretty terrible for Google to have case-sensitive IDs in the first place, and it feels odd for MSSQL to default to case insensitivity. So we're kind of stuck in the middle.

2020-10-15 00:46 UTC, zkagin commented
@dchess I found a _slightly_ more elegant way of doing it that runs a special MSSQL query before the raw SQL.

2020-10-23 22:49 UTC, zkagin commented
@dchess This took me longer than I thought, but I finally think I fixed it. The problem was that Postgres doesn't allow deleting from a CTE, and with no unique identifier when there are duplicate rows, there was no real mechanism for selecting and deleting one. I tried a ton of different SQL queries, as well as writing to a temp table and doing deletes after every batch rather than at the end, and nothing else I could find was both performant and didn't require separate queries for Postgres and MSSQL.

It's not the most elegant, but I think long-term we are going to want a unique auto-incrementing ID in all tables anyways. The problem we have now is that tables are created through dataframes when we should probably instead be creating them through the ORM. But that's something we can do another day.

Let me know what you think of this approach and if it works correctly for you.

2020-12-03 02:23 UTC, dchess commented
@zkagin I was able to test this against production and it was successful. However, we won't be able to put this logic into production in such a way that we can limit our queries to only current year until similar preservation logic is applied to the other endpoints as well. In particular course, student, teacher, and coursework are all necessary to be preserved with this append rather than truncate logic. 

What do you think about opening a dev branch to begin merging these changes against and then we can run a release process to merge to main?

2021-08-19 21:15 UTC, closed without merging